### ISSUE TITLE
Create a new Boost POW job script API endpoint is not working for me 

### ISSUE THREAD

**Issue by ielvisd** [pow-co/boostpow-api#33]
The endpoint to create new Boost POW job scripts is not working for me: 
https://pow.co/api#/boostpow/getApiV1BoostpowTx_idNew

<img width="1407" alt="Screenshot 2022-11-17 at 8 29 19 AM" src="https://user-images.githubusercontent.com/27535087/202502468-e4a5b694-6330-4992-8616-c7b0238c24b2.png">

**Comment by owenkellogg** [comment]
This is now resolved:

https://pow.co/api/v1/boostpow/87f55d0f435217bbf4824cdc4c6e5c6d75fda75a21dba3961973b1b46ff5abbd/new?currency=USD&value=1
